In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.4'

In [3]:
import numpy as np



In [4]:
np.__version__

'1.16.4'

## python List的特点

In [5]:
import array


In [6]:
arr = array.array('i',[i for i in range(10)])

In [7]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[5] = 'machine learning'

TypeError: an integer is required (got type str)

In [9]:
arr[5] = 100

In [10]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy.array

In [11]:
nparr = np.array([i for i in range(10)])

In [12]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [14]:
nparr.dtype

dtype('int32')

In [15]:
nparr[5] = 5.0

In [16]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr.dtype

dtype('int32')

In [18]:
nparr[5] = 5.12

In [19]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr2 = np.array([1,2,3.0])

In [21]:
nparr2.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(10).dtype


dtype('float64')

In [24]:
np.zerps((3,5))

AttributeError: module 'numpy' has no attribute 'zerps'

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full(shape = (3,5),fill_value = 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

 ## arange

In [31]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [35]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [36]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [37]:
np.random.randint(0,10)

3

In [38]:
np.random.randint(0,10,10)

array([3, 0, 5, 3, 9, 3, 6, 7, 0, 0])

In [39]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.random.randint(4,8,size = 10)

array([6, 4, 7, 5, 6, 5, 5, 7, 5, 7])

In [41]:
np.random.randint(4,8,size = (3,5))

array([[5, 6, 7, 5, 7],
       [4, 5, 4, 7, 5],
       [5, 7, 5, 6, 4]])

In [44]:
np.random.seed(666)

In [45]:
np.random.randint(4,8,size = (3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [46]:
np.random.seed(666)
np.random.randint(4,8,size = (3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [47]:
np.random.random()

0.2811684913927954

In [48]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [49]:
np.random.random((3,5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [50]:
np.random.normal()

0.7760516793129695

In [52]:
np.random.normal(10,100)

16.102403954600113

In [53]:
np.random.normal(0,1,(3,5))

array([[ 1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ,  0.03185388],
       [-0.19206285,  0.78611284, -1.69046314, -0.98873907,  0.31398563],
       [ 0.39638567,  0.57656584, -0.07019407,  0.91250436,  1.00470497]])

In [54]:
np.random.normal?


In [55]:
np.random?


In [58]:
x = np.arange(10)

In [59]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x = np.arange(10)

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [63]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
2 * x = 24 - 4 * x

SyntaxError: can't assign to operator (<ipython-input-64-6f2b719a36b0>, line 1)

In [65]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False])

In [66]:
x = np.arange(16)

In [67]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
X = np.reshape(x,(4,-1))

In [69]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
X[X[:,3] % 3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [ ]:

x = np.linspace(0,10,100)

In [ ]:
x

In [1]:
import numpy as np
import matplotlib.pyplot as plt
raw_data_X = [[3.3912,2.3384],
             [3.1134,1.7815],
             [1.3433,3.3685],
             [3.5822,4.6791],
             [2.2823,2.8661],
             [7.4234,4.6965],
             [5.7450,3.5339],
             [9.1721,2.5111],
             [7.7927,3.4240],
             [7.9398,0.7916]]
raw_data_y = [0,0,0,0,0,1,1,1,1,1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

In [2]:
X_train.shape[0]

10

In [3]:
x = np.array([8.0936,3.3657])

In [4]:
x.shape[0]

2

In [5]:
x.shape

(2,)