In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.4'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.4'

## python List的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[5] = 'machine learning'
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

注：List对所存数据的数据类型不敏感

In [9]:
import array

In [10]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy.array

In [12]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr[5]

5

In [14]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [15]:
nparr.dtype

dtype('int32')

In [16]:
nparr[5] = 5.0

In [17]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr.dtype

dtype('int32')

In [19]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr.dtype

dtype('int32')

In [21]:
nparr2 = np.array([1,2,3.0])
nparr2

array([1., 2., 3.])

In [22]:
nparr2.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10).dtype

dtype('float64')

In [25]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.full(shape = (3,5),fill_value = 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [30]:
np.full(shape = (3,5),fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

 ## arange

In [31]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

注：range的步长是不能传入浮点数的，而numpy中的arange是可以的

In [32]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [35]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

注：第三个参数表示等长的截取10个点，包括0和20

In [36]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [37]:
np.random.randint(0,10)

3

In [38]:
np.random.randint(0,10,10)

array([7, 8, 3, 3, 7, 1, 0, 5, 3, 6])

注：生成数组，长度为10

In [39]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.random.randint(4,8,size = 10)

array([5, 4, 7, 7, 7, 4, 4, 7, 7, 5])

In [41]:
np.random.randint(4,8,size = (3,5))

array([[6, 6, 7, 6, 4],
       [7, 4, 5, 7, 7],
       [7, 4, 6, 6, 4]])

注：生成3✖5的矩阵

In [42]:
np.random.randint(4,8,size = (3,5))

array([[6, 7, 6, 4, 7],
       [5, 6, 4, 5, 7],
       [6, 6, 4, 7, 4]])

In [43]:
np.random.seed(666)
np.random.randint(4,8,size = (3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

注：随机种子，使生成的随机数保持一致

In [44]:
np.random.random()

0.2811684913927954

In [45]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [46]:
np.random.random((3,5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [47]:
np.random.normal()

0.7760516793129695

注：均值为0，方差为1 的正态分布

In [48]:
np.random.normal(10,100)

128.06359754812632

注：均值为10，方差为100 的正态分布

In [49]:
np.random.normal(0,1,(3,5))

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

注：生成3✖5的随机矩阵

In [50]:
np.random.normal?

注：查询函数相应文档

In [51]:
np.random?

## Numpy.array的基本操作

In [53]:
x = np.arange(10)

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x.ndim

1

In [56]:
x.shape

(10,)

In [57]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
X.shape

(3, 5)

In [59]:
X.ndim

2

In [60]:
x.size

10

In [61]:
X.size

15

## numpy.array 的数据访问

In [62]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x[0]

0

In [64]:
x[-1]

9

In [65]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
X[0][0]

0

注：numpy 中不建议这样写，建议写成下面形式

In [67]:
X[(2,2)]

12

In [68]:
X[2,2]

12

In [69]:
x[0:5]

array([0, 1, 2, 3, 4])

In [70]:
x[:5]

array([0, 1, 2, 3, 4])

In [71]:
x[5:]

array([5, 6, 7, 8, 9])

In [72]:
x[::2]

array([0, 2, 4, 6, 8])

In [73]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [74]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [76]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [77]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [78]:
X[0]

array([0, 1, 2, 3, 4])

In [79]:
X[0,:]

array([0, 1, 2, 3, 4])

In [80]:
X[:,0]

array([ 0,  5, 10])

In [81]:
subX= X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [82]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [83]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [84]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [86]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [87]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [88]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Reshape

In [89]:
x.shape

(10,)

In [90]:
x.ndim

1

In [91]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
A = x.reshape(2,5)

In [94]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [97]:
x.shape

(10,)

In [98]:
B.shape

(1, 10)

In [99]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [100]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [101]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 合并操作

In [102]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [103]:
x

array([1, 2, 3])

In [104]:
y

array([3, 2, 1])

In [105]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [106]:
z = np.array([66,66,66])

In [107]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 66, 66, 66])

In [108]:
A = np.array([[1,2,3],
              [4,5,6]])

In [109]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [110]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [111]:
np.concatenate([A,z.reshape(1,-1)])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [66, 66, 66]])

In [112]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
A2 = np.concatenate([A,z.reshape(1,-1)])
A2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [66, 66, 66]])

In [114]:
np.vstack([A,z])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [66, 66, 66]])

In [115]:
B = np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [116]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 分割

In [117]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.split(x,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [119]:
np.split(x,[5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [120]:
A = np.arange(16).reshape((4,4))

In [121]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
x1,x2 = np.split(A,[2])

In [123]:
x1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [124]:
x2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
np.split(A,[2],axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [126]:
upper,lower = np.vsplit(A,[2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [127]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
left,right = np.hsplit(A,[2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [129]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [130]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [131]:
X,y = np.hsplit(data,[-1])

In [132]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [133]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [134]:
y[:,0]

array([ 3,  7, 11, 15])

## 运算

给定一个向量，让向量中每个数✖2

In [135]:
n = 10
L = [i for i in range(n)]

In [136]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [137]:
A=[2 * e for e in L]
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [138]:
%%time
A=[2 * e for e in L]

Wall time: 0 ns


In [139]:
L=np.arange(10)

In [140]:
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
A = 2 * L
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [142]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [143]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [144]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [145]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [146]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [147]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [148]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [149]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [150]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [151]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [152]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [153]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [154]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [155]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [156]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [157]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [158]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [159]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [160]:
A + B

array([[10, 11],
       [12, 13]])

In [161]:
A * B

array([[ 0, 10],
       [20, 30]])

In [162]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [163]:
A

array([[0, 1],
       [2, 3]])

In [164]:
A.T

array([[0, 2],
       [1, 3]])

In [165]:
C = np.full((3,3),666)
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

## 向量和矩阵的运算

In [166]:
v = np.array([1,2])

In [167]:
A

array([[0, 1],
       [2, 3]])

In [168]:
v + A

array([[1, 3],
       [3, 5]])

In [169]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [170]:
np.vstack([v]*A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [171]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [172]:
np.tile(v,(2,1)) + A

array([[1, 3],
       [3, 5]])

In [173]:
v

array([1, 2])

In [174]:
A

array([[0, 1],
       [2, 3]])

In [175]:
v.dot(A)

array([4, 7])

In [176]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [177]:
A

array([[0, 1],
       [2, 3]])

In [178]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [179]:
invA = np.linalg.inv(A)

In [180]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [181]:
X = np.arange(16).reshape((2,8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [182]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

注：非方阵的伪逆

In [183]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

## 聚合操作

In [184]:
L = np.random.random(100)
L

array([0.2427146 , 0.57043673, 0.57773404, 0.89274848, 0.12138544,
       0.66083873, 0.16459271, 0.09435837, 0.5876144 , 0.86014445,
       0.82936987, 0.65091808, 0.51832728, 0.00355049, 0.80309176,
       0.35932938, 0.42014544, 0.2026436 , 0.63279787, 0.18935861,
       0.1308497 , 0.75765845, 0.34158167, 0.52138487, 0.88302327,
       0.44914216, 0.23902229, 0.33014086, 0.26650938, 0.79768204,
       0.05551712, 0.12980746, 0.82262638, 0.36076783, 0.56970121,
       0.83023273, 0.44767601, 0.2132831 , 0.56115445, 0.71657783,
       0.7493205 , 0.58624783, 0.54759891, 0.0817732 , 0.40852941,
       0.63205157, 0.12168885, 0.27480879, 0.07770505, 0.15726591,
       0.14978044, 0.38535367, 0.70941476, 0.44518764, 0.01584702,
       0.99491381, 0.90632665, 0.05199571, 0.86100897, 0.51224649,
       0.0111548 , 0.49310591, 0.55102356, 0.27260476, 0.2311436 ,
       0.95858105, 0.66579831, 0.84015904, 0.14691185, 0.14394403,
       0.30843116, 0.37016398, 0.31852964, 0.56240025, 0.46409

In [185]:
sum(L)

48.178573904347246

In [186]:
np.sum(L)

48.17857390434729

In [187]:
np.min(L)

0.0035504869521352234

In [188]:
np.max(L)

0.9949138071844505

In [189]:
L.max()

0.9949138071844505

In [190]:
X = np.arange(16).reshape((4,-1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [191]:
np.sum(X)

120

In [192]:
np.sum(X,axis = 0)

array([24, 28, 32, 36])

In [193]:
np.sum(X,axis = 1)

array([ 6, 22, 38, 54])

In [194]:
np.prod(X)

0

In [195]:
np.prod(X + 1)

2004189184

In [196]:
np.mean(X)

7.5

In [197]:
np.median(X)

7.5

In [198]:
np.percentile(L,q=50)

0.48956877618183764

In [199]:
np.median(L)

0.48956877618183764

In [200]:
for percent in [0,25,50,75,100]:
    print(np.percentile(L,q=percent))

0.0035504869521352234
0.23705261771986857
0.48956877618183764
0.7247634951858691
0.9949138071844505


In [201]:
np.var(L)

0.07592847615424199

注：方差

In [202]:
np.std(L)

0.27555122237842095

注：标准差

## 索引

In [203]:
np.min(X)

0

In [204]:
L

array([0.2427146 , 0.57043673, 0.57773404, 0.89274848, 0.12138544,
       0.66083873, 0.16459271, 0.09435837, 0.5876144 , 0.86014445,
       0.82936987, 0.65091808, 0.51832728, 0.00355049, 0.80309176,
       0.35932938, 0.42014544, 0.2026436 , 0.63279787, 0.18935861,
       0.1308497 , 0.75765845, 0.34158167, 0.52138487, 0.88302327,
       0.44914216, 0.23902229, 0.33014086, 0.26650938, 0.79768204,
       0.05551712, 0.12980746, 0.82262638, 0.36076783, 0.56970121,
       0.83023273, 0.44767601, 0.2132831 , 0.56115445, 0.71657783,
       0.7493205 , 0.58624783, 0.54759891, 0.0817732 , 0.40852941,
       0.63205157, 0.12168885, 0.27480879, 0.07770505, 0.15726591,
       0.14978044, 0.38535367, 0.70941476, 0.44518764, 0.01584702,
       0.99491381, 0.90632665, 0.05199571, 0.86100897, 0.51224649,
       0.0111548 , 0.49310591, 0.55102356, 0.27260476, 0.2311436 ,
       0.95858105, 0.66579831, 0.84015904, 0.14691185, 0.14394403,
       0.30843116, 0.37016398, 0.31852964, 0.56240025, 0.46409

In [205]:
np.argmin(L)

13

In [206]:
L[13]

0.0035504869521352234

In [207]:
np.min(L)

0.0035504869521352234

## 排序和使用索引

In [208]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [209]:
np.random.shuffle(x)
x

array([ 3,  6,  7,  0, 11, 10,  9, 15,  2, 14,  4,  8, 12, 13,  1,  5])

In [210]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [211]:
x

array([ 3,  6,  7,  0, 11, 10,  9, 15,  2, 14,  4,  8, 12, 13,  1,  5])

In [212]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [213]:
X = np.random.randint(10,size=(4,4))
X

array([[4, 0, 9, 4],
       [3, 6, 4, 6],
       [0, 2, 5, 0],
       [8, 9, 8, 7]])

In [214]:
np.sort(X)

array([[0, 4, 4, 9],
       [3, 4, 6, 6],
       [0, 0, 2, 5],
       [7, 8, 8, 9]])

In [215]:
np.sort(X,axis=1)

array([[0, 4, 4, 9],
       [3, 4, 6, 6],
       [0, 0, 2, 5],
       [7, 8, 8, 9]])

In [216]:
np.sort(X,axis=0)

array([[0, 0, 4, 0],
       [3, 2, 5, 4],
       [4, 6, 8, 6],
       [8, 9, 9, 7]])

In [217]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [218]:
np.random.shuffle(x)
x

array([ 1,  9,  5,  3,  4,  7, 10,  0, 15,  2, 11, 12,  6, 14,  8, 13])

In [219]:
np.argsort(x)

array([ 7,  0,  9,  3,  4,  2, 12,  5, 14,  1,  6, 10, 11, 15, 13,  8],
      dtype=int64)

In [220]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  7,  6,  5,  8, 10, 11, 12,  9, 13, 14, 15])

In [221]:
np.argpartition(x,3)

array([ 7,  0,  9,  3,  4,  5, 12,  2, 14,  6, 10, 11,  1, 15, 13,  8],
      dtype=int64)

In [222]:
X

array([[4, 0, 9, 4],
       [3, 6, 4, 6],
       [0, 2, 5, 0],
       [8, 9, 8, 7]])

In [223]:
np.argsort(X,axis = 1)

array([[1, 0, 3, 2],
       [0, 2, 1, 3],
       [0, 3, 1, 2],
       [3, 0, 2, 1]], dtype=int64)

## Fancy Indexing

In [224]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [225]:
ind = [3,5,8]

In [226]:
x[ind]

array([3, 5, 8])

In [227]:
ind = np.array([[0,2],
                [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [228]:
X = x.reshape((4,-1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [229]:
row = np.array([0,1,2])
col = np.array([1,2,3])

In [230]:
X[row,col]

array([ 1,  6, 11])

In [231]:
X[0,col]

array([1, 2, 3])

In [232]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [233]:
col = [True,False,True,True]

In [234]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 的比较

In [235]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [236]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [237]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [238]:
x = np.arange(16)

In [239]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [240]:
np.sum(x<=3)

4

In [241]:
np.count_nonzero(x<=3)

4

In [242]:
np.any(x == 0)

True

In [243]:
np.any(x < 0)

False

In [244]:
np.all(x >= 0)

True

In [245]:
np.all(x > 0)

False

In [246]:
X = np.reshape(x,(4,-1))

In [247]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [248]:
np.sum(X % 2 == 0)

8

In [249]:
np.sum(X % 2 == 0,axis=1)

array([2, 2, 2, 2])

In [250]:
np.sum(X % 2 == 0,axis=0)

array([4, 0, 4, 0])

In [251]:
np.all(X > 0,axis=1)

array([False,  True,  True,  True])

In [252]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [253]:
np.sum((x > 3)&(x < 10))

6

In [254]:
np.sum((x % 2 == 0) | (x > 10))

11

In [255]:
np.sum(~(x == 0))

15

In [256]:
x[x<5]

array([0, 1, 2, 3, 4])

In [257]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [258]:
X[X[:,3] % 3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])