In [1]:
import numpy as np
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)

In [5]:
X_train.shape

(120, 4)

In [6]:
X_test.shape

(30, 4)

### sklearn 中的 StandardScaler

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
standardScaler = StandardScaler()

In [9]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
standardScaler.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [11]:
standardScaler.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [12]:
X_train1 = standardScaler.transform(X_train)

In [13]:
X_test_standard = standardScaler.transform(X_test)

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [16]:
knn_clf.fit(X_train1,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [17]:
knn_clf.score(X_test_standard,y_test)

1.0

### 使用自己定义的 StandardScaler

In [18]:
from playML.preprocessing import StandardScaler

In [19]:
standardScaler1 = StandardScaler()
standardScaler1.fit(X_train)

In [20]:
standardScaler1.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [21]:
standardScaler1.scaler_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [22]:
X_train2 = standardScaler.transform(X_train)

In [23]:
X_test_standard = standardScaler.transform(X_test)

In [24]:
from playML.KNN import KNNClassifier

In [25]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [26]:
knn_clf.fit(X_train2,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [27]:
knn_clf.score(X_test_standard,y_test)

1.0