### 测试算法

In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

## train_test_split(训练集与测试集分离)

方法一：将 X 与 y 合并后乱序再分离

In [9]:
Z = np.hstack([X,y.reshape(-1,1)])

In [10]:
np.random.shuffle(Z)

In [11]:
X1,y1 = np.split(Z,[4],axis=1)

In [12]:
test_ratio = 0.2
test_num = int(len(X1) * test_ratio)
test_num

30

In [13]:
X_test = X1[:test_num]
X_train = X1[test_num:]
y_test = y1[:test_num]
y_train = y1[test_num:]

In [14]:
X_train.shape

(120, 4)

In [15]:
y_train.shape

(120, 1)

In [16]:
y_test.shape

(30, 1)

In [17]:
X_test.shape

(30, 4)

方法二：将索引乱序后分离

In [18]:
shuffle_indexes = np.random.permutation(len(X))

In [19]:
shuffle_indexes

array([ 64,  18,  45,  72,  14,  75,  40, 120,  41,  16, 101, 114, 125,
       100, 126,  30,  11,  88, 128, 139,  67,  21,  82, 131,  81,  26,
        94,  29, 102,  15, 147,  90, 112,  34,  74, 123,  76,  71,  68,
       121, 133, 141, 135, 134, 105,  63, 127, 149, 143,  24,  53, 137,
        98,  86,  60,  39,  99,  13,  44,  77,   2,  50, 136,  93,  55,
       104, 138, 106,   0,  85,  35,  51,  49,  59,   8, 111,  37,  19,
        42, 132,  78,  12, 130,  70,  46,  83,  66,   4,  92,  89, 110,
        65,  61,  56,   9,   6,  58,  25, 146,  28,  31,  36, 119, 145,
       103,  27,  22,  52, 142,  33,  43,  97,  84,  10,  32, 113,  62,
       109, 129,  20, 148,  69,  23, 144,  87, 116,  17,   1,  79,  91,
        96,  95, 118, 107, 108,  73, 117,  38, 115,   3, 124,  54, 140,
         7, 122,  48,  57,  80,  47,   5])

In [20]:
test_ratio = 0.2
test_size = int(len(X)*test_ratio)

In [21]:
test_size

30

In [22]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [23]:
test_indexes

array([ 64,  18,  45,  72,  14,  75,  40, 120,  41,  16, 101, 114, 125,
       100, 126,  30,  11,  88, 128, 139,  67,  21,  82, 131,  81,  26,
        94,  29, 102,  15])

In [24]:
X_train = X[train_indexes]
y_train = y[train_indexes]
print(X_train.shape)

(120, 4)


## 使用自己写的算法

In [25]:
from playML.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [27]:
X_train.shape

(120, 4)

In [28]:
y_train.shape

(120,)

In [29]:
X_test.shape

(30, 4)

In [30]:
from playML.KNN import KNNClassifier

In [31]:
my_knn_clf = KNNClassifier(k=3)

In [32]:
my_knn_clf.fit(X_train,y_train)

KNN(k=3)

In [33]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([2, 2, 2, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 0, 2, 2, 0, 0])

In [34]:
y_test

array([2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 0, 2, 2, 0, 0])

In [35]:
sum(y_predict == y_test)

29

In [36]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667